# Use the official dbt-snowflake simage
FROM ghcr.io/dbt-labs/dbt-postgres:1.8.latest

# Set a working directory inside the container
WORKDIR /usr/app

# Copy your dbt project files into the container (optional for docker-compose)
COPY . /usr/app
